language: php
php:
- 7.0
sudo: false
install:
- composer config --global github-oauth.github.com $GITHUB_TOKEN_COMPOSER
- travis_retry composer install --no-interaction --no-scripts
- npm install -g npm@latest
- npm install
- node_modules/.bin/gulp
script:
- vendor/bin/phpunit
after_success:
- rm -Rf node_modules
- composer update --no-dev
- zip -r cachet-cf-bundled ./* .bp-config
deploy:
  provider: releases
  api_key:
    secure: EwBnKdHw2/BFkf8sowV95uIJjZTL+Wk6pojPbH+zQMpF4WuWAg+NX95hNy+iv19PfQVkldNRP12OzUAwt1+7fUrgplut8kG5BD+2YMd2uis6yrIemFQbqeBjAvqQCm8h5sVATrlTcMRuhNHPmjvDc6i13emL/ef/n0ZkKulGrr+0vDcJO/xDmCbhXCeVuJE2Nevsp66XyZkxvCw/ukroK6NaZMj9otcvlvJiVKJ7U2AVdYAFFVzo9tLV8j/WigSQvSAN3qBBNjsuiHF2bQoH04TEqXw26VN1GrJljHBWu1HaPirB0AfE/RuhoPLTj+Ua+M+URoOvOgqhGRHynS7QJ6CYnuGdhKLYaD5K+KyKesM+1pyN+JTy+A0VOdNd4HkpU6HkE7S2b4lEJRlodcM8Hh9TbhIlQxDiVYzeYJ/OqaseAjdB8mjmE7XnljdUUapOl/nTWw+T01FUerWHoms9PvnoOOjdO2gsdmZvHMetiHkfN6Gy0thKxAaUpLAnjIb2S86lInT3zzkptUAo7qXDBQPI5sgwc+XlcxQPy27xfOQDcNu5jCFmjOcQq2JgBTsaw6cnp/i63YNzog8uD41y0u7OJC59h58JPWaqjdOZm6kZJUDkwR4rMXJoZC2pHM9Rapm8DSZ8uZlUJUnGbfNCr85H8pGOjiHtNw9yriSEn+U=
  file: cachet-cf-bundled.zip
  on:
    tags: true
    all_branches: true
env:
  global:
    secure: Z8cNv96Nf91ai6Jc9Zw8PS3AZajBSlyarpW0N3zRolIW/qsZIjb5OxPgiCRmoOMQJTlZtHvxLjez4u+E/5C6Wq7+AG+h31N3kQu2iIhiiQSidHGG50/HTqzBnapEtlN5QhzLY6IGBnWhutF/NkUiUpD3CNBBnSYw8XfNpj4+B59IHo1HfN64THD7jvNWiJoWkGdQeNcxRryNlabJiFq94cVtLvBcNb8VPeQy/sxMWFgeknvoIEdct/xfEMc0sA6Gz54kPqSOiNQKuQKrEErgVJVdWSyrBVfd0VQIN/4HZVFI1Lw1SG0epEwd467kskqCBMnXL9J0oTAZ0tszO4ptkCECXHqrH0UjYE+ajvAUZ7Dea/gk8sja2P3cE5b9WejdQiUgyfjhU2kqBkGPP+NiG5CIN3s0rIeMRAwZoh1Df9T8aiFohwlYFxMhRekKgOOUJi3LI2/nWK6MLgqeGvudKW86GpEbL39G3AsPuPsJLTnT5icNrJLSeBF4jHDHOdcqXz4XjMUGJ7j4Iy1lVEDeYZxC69MSUFLJ7GcInjKbTyTfTKc27oByH1SFsMwvi1jLChwmOT9fzhJyzhLcmq+BWlscfBhhAGcjyNqSq2lXAQi+sUD77uSrzLAyA9geiLsF9AEVJDi6nbv1kWEym4PYdycOXv0kf/RUSlB3Q/Xly2Y=

