language: php
php:
- 5.5.9
sudo: false
install:
- apt-get update
- apt-get install nodejs npm
- travis_retry composer install --no-interaction --no-scripts
- npm install
- node_modules/.bin/bower install
- node_modules/.bin/gulp
script:
- vendor/bin/phpunit
after_success:
- rm -Rf node_modules
- composer update --no-dev
- zip -r cachet-cf-bundled ./*
deploy:
  provider: releases
  api_key:
    secure: EwBnKdHw2/BFkf8sowV95uIJjZTL+Wk6pojPbH+zQMpF4WuWAg+NX95hNy+iv19PfQVkldNRP12OzUAwt1+7fUrgplut8kG5BD+2YMd2uis6yrIemFQbqeBjAvqQCm8h5sVATrlTcMRuhNHPmjvDc6i13emL/ef/n0ZkKulGrr+0vDcJO/xDmCbhXCeVuJE2Nevsp66XyZkxvCw/ukroK6NaZMj9otcvlvJiVKJ7U2AVdYAFFVzo9tLV8j/WigSQvSAN3qBBNjsuiHF2bQoH04TEqXw26VN1GrJljHBWu1HaPirB0AfE/RuhoPLTj+Ua+M+URoOvOgqhGRHynS7QJ6CYnuGdhKLYaD5K+KyKesM+1pyN+JTy+A0VOdNd4HkpU6HkE7S2b4lEJRlodcM8Hh9TbhIlQxDiVYzeYJ/OqaseAjdB8mjmE7XnljdUUapOl/nTWw+T01FUerWHoms9PvnoOOjdO2gsdmZvHMetiHkfN6Gy0thKxAaUpLAnjIb2S86lInT3zzkptUAo7qXDBQPI5sgwc+XlcxQPy27xfOQDcNu5jCFmjOcQq2JgBTsaw6cnp/i63YNzog8uD41y0u7OJC59h58JPWaqjdOZm6kZJUDkwR4rMXJoZC2pHM9Rapm8DSZ8uZlUJUnGbfNCr85H8pGOjiHtNw9yriSEn+U=
  file: cachet-cf-bundled.zip
  on:
    tags: true
    all_branches: true
