language: php
php:
- 7.0
sudo: false
install:
- composer config --global github-oauth.github.com $GITHUB_TOKEN_COMPOSER
- travis_retry composer install --no-interaction --no-scripts
script:
- echo "no script"
after_success:
- composer update --no-dev
- zip -r cachet-cf-bundled ./* .bp-config
deploy:
  provider: releases
  api_key:
    secure: AFC79rRSVQcC1rWNNJd3ylBxqRmZxA3rgKnZdibC9405OGOnvckZy3kOBRYhFdlIRI0mdeo414TuxQXxrMaZQC8iI67S7NdAGdc4CBhdhdIEb1kFbDcD2U4fpDH6p3QIBmQfhEoO0mqS39O9R5iNH/qS4ahFwBFedMLzTv6HyAijUlt79kogQHjKi3k0y5JJZi4mFoh67rfl/y38HJIOS16P2NEjUeLmA2gWMOGXj0QmQNPZ/0b909MP0dZzuhSreDGsaVP+byaI4SDeDX/oFkbcHntVIZYLRvkus7t+EsUgswYe3tqrxkRiQmvdrMmR0jIsv9OI9FtE9/O464+qAYizc8JxmIh5dfX/nM0y8KRI9D+uaQ8+YqQ5Q3BNe6xNWz//jLIogWi9g8yKzPMndg/zwtYvb2baXqsMuVjKCmqWMfVn64YX/pOVJJRNxhfc1mEaFOtFXN4/1xELd2/nZ1b6ZIh9IHybxvou2wtpmGpvhHwoaNMxsp4q3nYU/BNjohyLWo+lLIn9g8kqUFtyEYkKrpYQJW6TkHJhU/ABRdMMMq9U3rdxmGm1prnTtmLcEOtCRrfM/UPwJ0+pLpYECbVWeewy6VQ2xDfUBpL6Io2hj9xLKFPqz0QlrgzWCi6YsZHZ2HsmFIcizWWq1vnHrXER8ECDkVcaAl7WrC97M0Q=
  file: cachet-cf-bundled.zip
  on:
    tags: true
    all_branches: true
